### ISSUE TITLE
Why did you install express?

### ISSUE THREAD

**Issue by shiryz** [lotus-1/correncyNN#21]
https://github.com/lotus-1/correncyNN/blob/master/package.json#L36

That shouldn't be in the dev dependencies or dependencies for now, not sure how it got there

**Comment by Noorb7188** [comment]
I think it's when I tried to deploy my app to Heroku , I tried like a million things , but eventually it worked with the help of Mynah :heart_eyes: 
I'll fix it .. :sunglasses:
